name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Change to your region

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name movieverse \
            --deployment-group-name movieverse_deployment \
            --revision revisionType=GitHub,gitHubLocation={repository=my-repo,commitId=${GITHUB_SHA}} \
            --description "Deploying new changes"
